name: Cron Scheduling Job Workflow

on:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print scheduled message
        run: echo "Scheduled workflow executed"
