name: cron scheduling job workflow

on:
  schedule:
    - cron: "00***"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "schedule a workflow executed"
